### ISSUE TITLE
Create a dream UI for Hackathon organized by CSI-CATT DMCE

### ISSUE THREAD

**Issue by ReshmaZore** [CSI-DMCE-2024/Non-Code-Hacktoberfest-2024#1]

**Comment by Khanvilkarshravani27** [comment]
Hello Maintainer , Can I work on this issue?

**Comment by Apurva-29** [comment]
Hello maintainers I want to work on this issue

**Comment by AdK819** [comment]
Hello Maintainers! Aditi here
May I work on this issue?

**Comment by ReshmaZore** [comment]
> Hello Maintainer , Can I work on this issue?

@Khanvilkarshravani27 go for it and complete it within 24 hrs

**Comment by mayureshh27** [comment]
> Hello Maintainers! Aditi here May I work on this issue?

Start Working and complete it asap 24hr time
