### ISSUE TITLE
Create React/Node.js/Django Basics Cheatsheet

### ISSUE THREAD

**Issue by mayureshh27** [CSI-DMCE-2024/Non-Code-Hacktoberfest-2024#10]
Develop concise and informative cheatsheets for basic concepts in React, Node.js, and Django. The React cheatsheet should cover topics like JSX, components, props, state, and hooks, serving as a quick reference guide for beginners.

**Comment by dinaaz-khan** [comment]
Hey leads i want work on this issue

**Comment by AdK819** [comment]
Hello Maintainers! Aditi here
May I work on this issue?

**Comment by ReshmaZore** [comment]
> Hello Maintainers! Aditi here May I work on this issue?

@AdK819 Start Working and complete it asap

**Comment by Junkie-source** [comment]
Hello Maintainers, i want to work on this issue?

**Comment by Apurva-29** [comment]
Hello maintainers I want to work on this issue

**Comment by mayureshh27** [comment]
> Hello Maintainers, i want to work on this issue?

@Junkie-source Start Working and complete it asap 24hr time
