### ISSUE TITLE
Create an animated video or GIF that visually explains how the project works, its features.

### ISSUE THREAD

**Issue by ReshmaZore** [CSI-DMCE-2024/Non-Code-Hacktoberfest-2024#2]
Eg. VS code installation guide (for Windows and Mac)

**Comment by Parth-code286** [comment]
Hey maintainer i want to work on this issue

**Comment by ReshmaZore** [comment]
> Hey maintainer i want to work on this issue

@Parth-code286 start ur work, All the best

**Comment by ReshmaZore** [comment]
> Hey maintainer i want to work on this issue

@Parth-code286 the animation is quite okayy..try to make best of it u can add actual process while the visual is speaking...and complete it asap

**Comment by SanikaSalunkhe1** [comment]
Hey maintainer can I work on this issue?

**Comment by ReshmaZore** [comment]
> Hey maintainer can I work on this issue?

@TechMe103 Go for it

**Comment by SanikaSalunkhe1** [comment]
Sure
