### ISSUE TITLE
Document the Mastering JavaScript Workshop conducted

### ISSUE THREAD

**Issue by ReshmaZore** [CSI-DMCE-2024/Non-Code-Hacktoberfest-2024#4]

**Comment by dinaaz-khan** [comment]
Hey leads, I want to work on this issue.

**Comment by tghosh294** [comment]
I want to work on this

**Comment by ReshmaZore** [comment]
> I want to work on this

@tghosh294 start workingg

**Comment by ReshmaZore** [comment]
> Hey leads, I want to work on this issue.

@Dinaazk start working

**Comment by nikamroshan** [comment]
hey maintainer , i want to work on this issue

**Comment by mayureshh27** [comment]
> hey maintainer , i want to work on this issue

@devRoshan-25 Gor fot it and try to complete asap u have 24hrs time

**Comment by tghosh294** [comment]
hello, I want to work on this issue
