### ISSUE TITLE
Design Event Badges for Participants

### ISSUE THREAD

**Issue by mayureshh27** [CSI-DMCE-2024/Non-Code-Hacktoberfest-2024#41]
Create lanyard badge designs for participants attending the upcoming workshops and events.

Tasks:

Design badges that include the participant’s event name, and logo.

**Comment by AdK819** [comment]
Hello Maintainers! Aditi here
May I work on this issue?

**Comment by dinaaz-khan** [comment]
Hey maintainers, I want to work on this issue

**Comment by mayureshh27** [comment]
> Hello Maintainers! Aditi here May I work on this issue?

go for it and complete it within 24 hrs

**Comment by Apurva-29** [comment]
Hello maintainers I want to work on this issue
