### ISSUE TITLE
Create an Instagram post and a story post to promote our upcoming React js , Django and Node js workshop

### ISSUE THREAD

**Issue by ReshmaZore** [CSI-DMCE-2024/Non-Code-Hacktoberfest-2024#5]

**Comment by VedantDalvi05** [comment]
Hey leads i want to work on this issue

**Comment by ReshmaZore** [comment]
> Hey leads i want to work on this issue

@VedantDalvi05 start ur work

**Comment by Khanvilkarshravani27** [comment]
Hello Maintainer , Can I work on this issue?

**Comment by Apurva-29** [comment]
Hello maintainers I want to work on this issue

**Comment by AdK819** [comment]
Hello Maintainers! Aditi here
May I work on this issue?

**Comment by ReshmaZore** [comment]
> Hey leads i want to work on this issue

@VedantDalvi05 go for it , and complete it within 24hours.

**Comment by Apurva-29** [comment]
Hello maintainers I want to work on this issue

**Comment by mayureshh27** [comment]
> Hello maintainers I want to work on this issue
@Apurva-29 go for it , and complete it within 24hours.
