### ISSUE TITLE
Create a Cheat Sheet of Git Commands

### ISSUE THREAD

**Issue by ReshmaZore** [CSI-DMCE-2024/Non-Code-Hacktoberfest-2024#6]

**Comment by Aditya-jambhale** [comment]
I am interested to work on this issue

**Comment by VaradDhoke** [comment]
Hey leads. Varad Dhoke here. I'd like to work on this issue.

**Comment by dinaaz-khan** [comment]
Hey leads, I want to work on this issue.

**Comment by tghosh294** [comment]
I want to work on this

**Comment by mayureshh27** [comment]
> I am interested to work on this issue

@Aditya-jambhale start working on it

**Comment by ReshmaZore** [comment]
> I want to work on this

Start working on it tghosh294

**Comment by ReshmaZore** [comment]
> Hey leads, I want to work on this issue.

@Dinaazk start workingg

**Comment by ReshmaZore** [comment]
> Hey leads. Varad Dhoke here. I'd like to work on this issue.

@TickleFuse09 Start workingg

**Comment by Apurva-29** [comment]
Hello maintainers I want to work on this issue

**Comment by AdK819** [comment]
Hello Maintainers! Aditi here
May I work on this issue?

**Comment by kambleprathamesh** [comment]
Issue Resolved!
